services:
  # Main CLI service for interactive commands
  inbox-sentinel:
    build: .
    container_name: inbox-sentinel
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./testfiles:/app/testfiles
    environment:
      - PYTHONPATH=/app
    command: ["tail", "-f", "/dev/null"]  # Keep container running for exec commands
    restart: unless-stopped